<a href="https://colab.research.google.com/github/geun1/geun1/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow.compat.v1 as tf #설치한건v2인데 쓸거는 v1이라서 .compat.v1붙여줌
tf.disable_eager_execution() #v1으로 쓰기 위해서 사용

hello = tf.constant("hello, tensorflow") #constant명령어는 hello를 node로 설정해주는 것
sess = tf.Session()
print(sess.run(hello))

b'hello, tensorflow'


In [18]:
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0)
node3 = tf.add(node1,node2)

In [3]:
print("node1: ",node1,"node2: ",node2)
print("node3: ",node3)

node1:  Tensor("Const_1:0", shape=(), dtype=float32) node2:  Tensor("Const_2:0", shape=(), dtype=float32)
node3:  Tensor("Add:0", shape=(), dtype=float32)


In [5]:
sess = tf.Session()
print("sess.run(node1,node2): ",sess.run([node1,node2]))
print("sess.run(node3): ",sess.run(node3))

sess.run(node1,node2):  [3.0, 4.0]
sess.run(node3):  7.0


In [24]:
a =tf.placeholder(tf.float32)
b=tf.placeholder(tf.float32)

adder_node = a+b
print(sess.run(adder_node, feed_dict={a:3,b:2.5}))
print(sess.run(adder_node, feed_dict={a:[1, 2],b:[2.3, 0]}))

5.5
[3.3 2. ]


In [27]:
import numpy as np
import pprint as pp #matrix 형태로 표현해줌
t= np.array([0.,1.,2.,3.,4.,5.,6.])
pp.pprint(t)
print(t)
print(t.ndim) #rank (차원)
print(t.shape) #shape

array([0., 1., 2., 3., 4., 5., 6.])
[0. 1. 2. 3. 4. 5. 6.]
1
(7,)


In [45]:
t= tf.constant([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]]])
tf.shape(t).eval(session =sess)
pp.pprint(t)
print(t)

<tf.Tensor 'Const_30:0' shape=(1, 2, 3, 4) dtype=int32>
Tensor("Const_30:0", shape=(1, 2, 3, 4), dtype=int32)


matrix 곱: 
          (a x b)와 (b x c)의 행렬곱은 (a x c) 형태
          

In [50]:
matrix1 = tf.constant([[1.,2.],[2.,3.]])
matrix2 = tf.constant([[2.],[3.]])
print("matrix1 shape: ",matrix1.shape)
print("matrix2 shape: ",matrix2.shape)
tf.matmul(matrix1,matrix2).eval(session=sess)

matrix1 shape:  (2, 2)
matrix2 shape:  (2, 1)


array([[ 8.],
       [13.]], dtype=float32)

In [52]:
#단순 곱은 matrix곱과는 다름

(matrix1*matrix2).eval(session=sess)

array([[2., 4.],
       [6., 9.]], dtype=float32)

reduce mean, axis

In [54]:
tf.reduce_mean([1,2],axis=0).eval(session=sess)
# int로 평균을 냈기 때문에 결과값도 int로 1.5가 아닌 1로 표현됨

1

In [56]:
x = [[1.,2.],
     [3.,4.]]
tf.reduce_mean(x).eval(session=sess)
# axis를 설정안해주면 전체의 평균

2.5

In [57]:
tf.reduce_mean(x,axis=0).eval(session=sess)
#axis=0 은 열(세로)

array([2., 3.], dtype=float32)

In [59]:
tf.reduce_mean(x,axis=1).eval(session=sess)
#axis=1 은 행 (가로)


array([1.5, 3.5], dtype=float32)

In [60]:
tf.reduce_mean(x,axis=-1).eval(session=sess)
#axis=-1 은 마지막 -> 여기서는 1 -> 행 (가로)

array([1.5, 3.5], dtype=float32)

redue_sum -> 합구하기


In [61]:
tf.reduce_sum(x,axis=0).eval(session=sess)

array([4., 6.], dtype=float32)

In [62]:
tf.reduce_sum(x,axis=1).eval(session=sess)

array([3., 7.], dtype=float32)

In [63]:
tf.reduce_sum(x,axis=-1).eval(session=sess)

array([3., 7.], dtype=float32)



argmax -> 최댓값의 위치 구하기


In [70]:
x= [[0.,1.,2.],
    [3.,4.,5.]]

In [71]:
tf.argmax(x).eval(session=sess)

array([1, 1, 1])

In [72]:
tf.argmax(x,axis=0).eval(session=sess)
# 열(세로)에서 [[1,2][3,4]] 최댓값들은 3 이랑 4 
# 따라서 위치가 각각 1,1 이므로 [1,1]로 표현됨

array([1, 1, 1])

In [73]:
tf.argmax(x,axis=1).eval(session=sess)

array([2, 2])

reshape -> 원하는 모양으로 matrix를 만들어줌

In [75]:
t=np.array([[[0,1,2],
           [2,3,4]],
           [[5,6,7],
            [7,8,9]]])
t.shape

(2, 2, 3)

In [77]:
t.reshape(-1,3)
# matrix의 행렬의 크기를 바꿔줌 

array([[0, 1, 2],
       [2, 3, 4],
       [5, 6, 7],
       [7, 8, 9]])

In [78]:
tf.reshape(t,shape=[-1,3]).eval(session=sess)
#위와 결과값은 같지만 위는 numpy에서 바꿔주는거고 아래는 tensorflow에서

array([[0, 1, 2],
       [2, 3, 4],
       [5, 6, 7],
       [7, 8, 9]])

one hot -> 원소의 위치를 알려주는 것

In [80]:
tf.one_hot([[0],[1],[2],[3]],depth=3).eval(session=sess)


array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[0., 0., 0.]]], dtype=float32)

In [81]:
t=tf.one_hot([[0],[1],[2],[3]],depth=3).eval(session=sess)
tf.reshape(t,shape=[-1,3]).eval(session=sess)
# one_hot을 사용하면 하나씩 늘어나기때문에 줄이는 과정이필요

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)

casting -> 데이터의 타입을 바꿔주는것

In [83]:
tf.cast([1.2,5.3,1.4],tf.int32).eval(session=sess)


array([1, 5, 1], dtype=int32)

stack -> 데이터들을 쌓는것

In [84]:
x= [1,2]
y= [3,4]
z= [5,6]
tf.stack([x,y,z]).eval(session=sess)


array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [85]:
tf.stack([x,y,z],axis=1).eval(session=sess)

array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)